version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing dependencies...
      - npm install
      - ./scripts/install_handler_deps.sh
  build:
    commands:
      - npm run test:unit
