AWSTemplateFormatVersion: '2010-09-09'
Description: A RESTful API for tracking lists of trending items.
Resources:
  GetTrendingItems:
    Properties:
      CodeUri: s3://trend-tracker/d465bbdad91c7655b6eb91eb5e1e4f7d
      Description: Handler for getting a list of trending items
      Events:
        GetTrendingItemsAPI:
          Properties:
            Method: GET
            Path: /
            RequestParameters:
              method.request.querystring.trendListId:
                Required: true
          Type: Api
      FunctionName: GetTrendingItems
      Handler: index.handler
      Policies:
      - Statement:
        - Action:
          - dynamodb:Query
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/InteractionCounts/index/trendListId-interactionCount-index
        Version: '2012-10-17'
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  InteractionCounts:
    Properties:
      AttributeDefinitions:
      - AttributeName: trendListId
        AttributeType: S
      - AttributeName: itemId
        AttributeType: S
      - AttributeName: interactionCount
        AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: trendListId
        KeyType: HASH
      - AttributeName: itemId
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: trendListId-interactionCount-index
        KeySchema:
        - AttributeName: trendListId
          KeyType: HASH
        - AttributeName: interactionCount
          KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
      TableName: InteractionCounts
    Type: AWS::DynamoDB::Table
  Interactions:
    Properties:
      AttributeDefinitions:
      - AttributeName: itemId
        AttributeType: S
      - AttributeName: expirationTimestamp
        AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: itemId
        KeyType: HASH
      - AttributeName: expirationTimestamp
        KeyType: RANGE
      TableName: Interactions
    Type: AWS::DynamoDB::Table
  RecordInteraction:
    Properties:
      CodeUri: s3://trend-tracker/5591f502ee650095196a7d4c4caf37cd
      Description: Handler for recording an user's interaction with an item
      Events:
        RecordInteractionAPI:
          Properties:
            Method: POST
            Path: /
            RequestParameters:
              method.request.querystring.trendListId:
                Required: true
          Type: Api
      FunctionName: RecordInteraction
      Handler: index.handler
      Policies:
      - Statement:
        - Action:
          - dynamodb:PutItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/Interactions
        - Action:
          - dynamodb:UpdateItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/InteractionCounts
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:lambda:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :function:GetTrendingItems
        Version: '2012-10-17'
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  WipeExpiredInteractions:
    Properties:
      CodeUri: s3://trend-tracker/3dd1313d0444e36ac41cad424c347aac
      Description: Function that is run at regular intervals to remove expired records
      Events:
        ScheduledRule:
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
          Type: Schedule
      FunctionName: WipeExpiredInteractions
      Handler: index.handler
      Policies:
      - Statement:
        - Action:
          - dynamodb:Scan
          - dynamodb:DeleteItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/Interactions
        - Action:
          - dynamodb:UpdateItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/InteractionCounts
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:lambda:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :function:GetTrendingItems
        Version: '2012-10-17'
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
